name: Build and Push Docker image to ECR

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region eu-west-2


    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Update Dockerfile
      run: |
        sed -i 's/FROM wiremock\/wiremock/FROM wiremock\/wiremock\n\nCOPY mappings\/ \/home\/wiremock\/mappings\/\nCOPY __files\/ \/home\/wiremock\/__files\//g' Dockerfile

    - name: Build Docker image
      run: |
        docker build -t ej-wiremock .
    
    - name: Tag Docker image with ECR repository URL
      run: |
        docker tag my-custom-wiremock:latest ${{ steps.login-ecr.outputs.registry }}/<ecr-repository-name>:latest

    - name: Push Docker image to ECR
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/wiremock-container-repo:latest
