name: Build and Push Docker image to ECR

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # -name: Debug step
    #  run: ls

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Update Dockerfile
      run: |
        sed -i 's/FROM wiremock\/wiremock/FROM wiremock\/wiremock\n\nCOPY mappings\/ \/home\/wiremock\/mappings\/\nCOPY __files\/ \/home\/wiremock\/__files\//g' Dockerfile

    - name: Build Docker image
      run: |
        docker build -t wiremock-image .
    
    - name: Tag Docker image with ECR repository URL
      run: |
        docker tag wiremock-image:latest 183663748910.dkr.ecr.eu-west-1.amazonaws.com/wiremock-image:latest

    - name: Push Docker image to ECR
      run: |
        docker push 183663748910.dkr.ecr.eu-west-1.amazonaws.com/wiremock-image:latest

    - name: Update Fargate Service
      run: |
        aws ecs update-service --cluster wiremock-cluster --service wiremock-service-5 --region eu-west-1 --force-new-deployment
