name: Build and Push Docker image to ECR

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # -name: Debug step
    #  run: ls

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Update Dockerfile
      run: |
        sed -i 's/FROM wiremock\/wiremock/FROM wiremock\/wiremock\n\nCOPY mappings\/ \/home\/wiremock\/mappings\/\nCOPY __files\/ \/home\/wiremock\/__files\//g' Dockerfile

    - name: Build Docker image
      run: |
        docker build -t ej-wiremock .
    
    - name: Tag Docker image with ECR repository URL
      run: |
        docker tag ej-wiremock:latest ${{ steps.login-ecr.outputs.registry }}/wiremock-container-repo:ej-wiremock-latest

    - name: Push Docker image to ECR
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/wiremock-container-repo:ej-wiremock-latest

    - name: Update Fargate Service
      run: |
        aws ecs update-service --cluster WireMockTestCluster1 --service wiremock-loadbalanced --region eu-west-2 --force-new-deployment
